import turtle
from turtle import*
wn=turtle.Screen()
wn.bgcolor("blue")
tess=Turtle()
tess.shape("circle")
tess.color("yellow")
tess.speed(1)
tess.right(30)
tess.forward(60)
for i in range(2):
 tess.stamp()
 tess.right(150)
 tess.forward(50)
 tess.left(150)
 tess.forward(100)
tess.stamp()
tess.right(150)
tess.forward(100)
tess.left(90)
tess.forward(100)
tess.right(90)
tess.forward(50)
tess.right(90)
tess.forward(100)
tess.left(90)
tess.forward(100)
for i in range(2):
   tess.stamp()
   tess.right(150)
   tess.forward(100)
   tess.left(150)
   tess.forward(50)
tess.stamp()
tess.right(150)
tess.forward(60)
turtle.bye()
 
